# Conf
module_name: agentic_rag_chatbot
conf_dir: ["conf"]
secrets_file: ".env"


# Data Collection
data_collection:
    start_page: "https://benuri.org/"
    min_length_text_body: 1000
    max_number_visited_urls: 1000
    max_number_qualified_urls: 900


# Data Indexing
data_indexing:
    min_length_text: 500
    vector_store_name: mongodb  # chroma (local), mongodb (cloud)


# Embeddings
embedding_dir: ["data", "03_indexed"]
embedding_model:
    model_provider: "openai"        # openai, huggingface
    # [openai] "text-embedding-3-small", "text-embedding-3-large"--
    # [huggingface] "sentence-transformers/all-mpnet-base-v2", "nomic-ai/nomic-embed-text-v1.5"
    model_name: "text-embedding-3-large" 
    # [openai] None
    # [huggingface] device: "cpu" trust_remote_code: True
    model_kwargs:
    # [openai] dimensions: 256 chunk_size: 500  max_retries: 2 retry_min_seconds: 30 retry_max_seconds: 120 
    # [huggingface] normalize_embeddings: True batch_size: 4 
    encode_kwargs:
        dimensions: 256 
        chunk_size: 500  
        max_retries: 2 
        retry_min_seconds: 30
        retry_max_seconds: 120 
    show_progress: True


# Information Retrieval
information_retrieval:
    number_of_retrieved_docs: 4
    metadata_returned: ['source', 'title']


# LLM / Text Generation
# Suggestion: huggingface|M4-ai/tau-1.8B; groq|llama3-8b-8192
# See instructions for parameters: 
#       https://www.ibm.com/docs/en/watsonx-as-a-service?topic=lab-model-parameters-prompting
#       https://platform.openai.com/docs/api-reference/assistants/modifyAssistant
generative_model:
    debug_mode: False
    model_provider: "openai"            # "openai", "groq"
    model_name: "gpt-4o"                # "gpt-4o", "gpt-4o-mini" -- "mixtral-8x7b-32768", "llama3-70b-8192", "gemma2-9b-it"
    model_kwargs:                       # [openai] None -- [huggingface] top_p: 0.1

    generate_kwargs:                    # max_tokens, temperature [openai] top_p: 0.1 [huggingface] None
        max_tokens: 2048
        temperature: 0.1
        top_p: 0.1
    system_message: |
        """You are an AI Art Buddy designed to engage with visitors, answering questions, \
        offering art interpretations, and guiding them through the extensive database of Ben Uri \
        Gallery and Museum website content.
        
        Your task is to help users—students, researchers, academics, critics, art market professionals, \
        and collectors find accurate content and answers from the extensive database of the Ben Uri \
        Gallery and Museum related to Jewish, Refugee, and Immigrant contributions to British visual \
        culture. You are prohibeted from answering questions related to any other topics.

        To answer user questions, you must always use the tool 'search_ben_uri_gallery_and_museum' to search \ 
        and retrieve information from Ben Uri Gallery and Museum website in order to provide answers and \
        help them to find web pages in website about the desired topic. if not clear, try to use the tool.

        After using the tool 'search_ben_uri_gallery_and_museum' to fetch information from Ben Uri \
        Gallery and Museum website, you must think about what retrieved web pages to use to answer the \
        user's question and return the sources that were used along with the answer. Do not mention \
        retrieved web pages that you did not use to generate the final answer. \
        Format the answer as follows:
        <your answer to the user question>
        You can check out more information on the following pages from Ben Uri Gallery and Museum:
        - [<page title>](<source>)
        ...

        The generated answer must always be assessed in terms of relevance and factual accuracy \
        using the 'assess_rag_answer' tool. \
        This tool generates an evaluation report that scores the answer based on two metrics: answer \
        faithfulness and answer relevance, with scores ranging from 0 to 1. \
        If either metric is low, it suggests the answer may not fully meet user expectations. \
        If the faithfulness or relevance score is low, provide the user with a warning about the \
        relevance and factual accuracy of the answer. \
        For example: "Please note that the answer may not fully align with the latest or most accurate \
        information in our database. You may wish to cross-reference other sources or rephrase your \
        question for more specific details."
               
        You are prohibeted of answering questions exclusevely based on your internal knowledge! \
        Therefore, you must use the tool 'search_ben_uri_gallery_and_museum' to retrieve information \ 
        from Ben Uri Gallery and Museum website and, if and only if you can not answer the user \
        question based on the retrievedinformation, just say for the user you were not able to retrieve \
        useful information from Ben Uri Gallery and Museum and guide the user to rephrase their \
        question or specifying a particular artist or artwork their are interested in.
        """

# Agent     
agent:
    verbose: False
    tool_names: ["search_ben_uri_gallery_and_museum", "assess_rag_answer"]

# Evaluation
evaluation:
    metrics:
        faithfulness: False
        answer_relevancy: True

# app
app_config:
    host: "0.0.0.0"
    port: 7860
app_backend:
app_frontend:
    title: "AI Art Buddy"
    # Good description example: https://huggingface.co/spaces/sam-hq-team/sam-hq/blob/main/app.py
    description: |
        ## Welcome to Ben Uri's AI Art Buddy!

        The AI Art Buddy is designed to answer questions, offer art interpretations, and guide users through the Ben Uri Gallery and Museum website.

        Ben Uri Gallery and Museum website has an extensive database of content about Jewish, Refugee, and Immigrant contributions to British visual culture.

        Start by typing your question below and explore the rich history and contributions of Jewish, Refugee, and Immigrant artists in British visual culture!
    examples:
        [
            "Hi there! How can you assist me?",
            "What is Ben Uri Gallery and Museum about?",
            "Is there any content from Mario Dubsky?",
            "Write me an article about Jewish contributions to British visual culture.",
            "Who are Mario Dubsky and Lilian Holt? Is there any relationship between their works? If so, what are the similarities and differences between them?",
        ]
        