# Conf
conf_dir: ["conf"]
secrets_file: ".env"


# Data Indexing
data_dir: ["data"]
ingestion_metadata_file: "webpage_ingestion_control.csv"
job_titles: ["Data Engineer", "Data Scientist", "Data Analyst", "Machine Learning Engineer"]


# Embeddings
embedding_dir: ["data", "03_indexed"]
embedding_model:
    model_name: "sentence-transformers/all-mpnet-base-v2" # "sentence-transformers/all-mpnet-base-v2", "nomic-ai/nomic-embed-text-v1.5"
    model_kwargs:
        device: "cpu" 
        trust_remote_code: True
    encode_kwargs:
        normalize_embeddings: True
        batch_size: 4
    show_progress: True


# Information Retrieval
information_retrieval:
    number_of_retrieved_docs: 2
    metadata_returned: ['source', 'title']


# LLM / Text Generation
# Suggestion: huggingface|M4-ai/tau-1.8B; groq|llama3-8b-8192
# See instructions for parameters: 
#       https://www.ibm.com/docs/en/watsonx-as-a-service?topic=lab-model-parameters-prompting
#       https://platform.openai.com/docs/api-reference/assistants/modifyAssistant
generative_model:
    model_provider: "groq"              # "openai", "groq"
    model_name: "llama3-70b-8192"       # "gpt-4o", -- "mixtral-8x7b-32768", "llama3-70b-8192", "gemma2-9b-it"
    model_kwargs:                       # top_p
        top_p: 0.7
    generate_kwargs:                    # max_tokens, temperature
        max_tokens: 512
        temperature: 0.3
    system_message: |
        """You are an AI Art Assistant designed to guide users through the Ben Uri Gallery and Museum website. \
        
        You task is help users—students, researchers, academics, critics, art market professionals, and \
        collectors find accurate content and answers related to Jewish, Refugee, and Immigrant contributions \ 
        to British visual culture from the extensive database of the Ben Uri Gallery and Museum. \
        
        To this end, you must use the tool 'search_ben_uri_gallery_and_museum' to search and retrieve \
        information from Ben Uri Gallery and Museum website in order to provide answers for the user's \
        queries and help them to find web pages in website about the desired topic.\
        
        The tool 'search_ben_uri_gallery_and_museum' will return the content in the following format:
            source: link of the web page 1
            title: title of the web page 1
            content: content of the web page 1

            source: link of the web page 2
            title: title of the web page 2
            content: content of the web page 2

        If you use the tool 'search_ben_uri_gallery_and_museum', you must think about what retrieved web \
        pages to use to answer an user's question and return the source the used information along with \
        the answer. Do not mention retrieved web pages that you do not use to generate the final answer. \
        Format the answert as follows:
        According to the Ben Uri Gallery and Museum, <your answer to the user question>
        You can check out more information on the following pages:
        - [<page title>](<source>)
        ...

        If you are not sure whether you should use the tool or respond based on your internal knowledge, \ 
        ask for further clarification. \

        If you choose to use your internal knowledge to answer a question related to the Ben Uri Gallery \
        and Museum content (Jewish, Refugee, and Immigrant contributions to British visual culture), \
        you must always ask the user if you should search the Ben Uri Gallery and Museum database.
        """

# Agent     
agent:
    verbose: False
    tool_names: ["search_ben_uri_gallery_and_museum"]


# app
app_config:
    host: "0.0.0.0"
    port: 7860
app_backend:
app_frontend:
    title: "AI Art Assistant"
    # Good description example: https://huggingface.co/spaces/sam-hq-team/sam-hq/blob/main/app.py
    description: |
        ## Welcome to Your AI Art Assistant!
        
        This AI assistant is designed to provide expert information about Jewish, Refugee, and Immigrant contributions to British visual culture from the extensive database of the Ben Uri Gallery and Museum.

        Start by typing your question below and explore the rich history and contributions of artists in British visual culture through the Ben Uri Gallery and Museum!
    examples:
        [
            "Hi there! How can you assist me?",
            "What is Ben Uri Gallery and Museum about?",
            "Is there any content from Joseph Ross?",
            "Tell me the most famous painting of the Jewish people.",
        ]
        